---
title: "PROBAST assessment"
author: "Till Adam"
date: "2023-12-20"
output: html_document
---


```{r}
#Load Packages
library(readxl)
library(flextable)
library(tidyverse)
```

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Reinstall all of the packages as declared in renv.lock
# renv::restore()

#library(knitr)
library(readxl)

# Compressed data table
library(officer)
library(flextable)

# Plotting
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(patchwork)
```

```{r}
#Loading and adjusting table
PROBAST <- readxl::read_excel(path = "Z:/PsyThera/Projekte_Meinke/Systematic_review/4_PROBAST_assessment/PROBAST_assessment.xlsx", sheet = "Main", col_names = FALSE)

PROBAST_transposed <- t(PROBAST)
PROBAST_transposed <- as.data.frame(PROBAST_transposed)
colnames(PROBAST_transposed) <- PROBAST_transposed[1, ]
PROBAST_transposed <- PROBAST_transposed[-1, ]
PROBAST_transposed <- PROBAST_transposed[,-1]
colnames(PROBAST_transposed)[1] <- "Question"
PROBAST_transposed$Question <- gsub("\n", "", PROBAST_transposed$Question)
PROBAST_transposed <- PROBAST_transposed[!grepl("comment", PROBAST_transposed[, 1]), ]

PROBAST_transposed
colnames(PROBAST_transposed)
str(PROBAST_transposed)
```

## Create flextable of summary table for publication
```{r Flextable, results = "show"}
# More info about settings in flextable: https://ardata-fr.github.io/flextable-book/cell-content.html

# Set defaults
set_flextable_defaults(
  font.size = 6,
  line_spacing = 1,
  padding.bottom = 2,
  padding.top = 2,
  padding.left = 0.2,
  padding.right = 0.2
)

# Initialize flex_table
apa_sumtable <- flextable(PROBAST_transposed)

#Subdividing table with colours
apa_sumtable <- hline(apa_sumtable, part = "body", i = c(3, 7, 14, 24), 
                      border = fp_border(color = "black", width = 1))

apa_sumtable <- bg(apa_sumtable, part = "body", i = c(3, 7, 14, 24), 
                   bg = "lightblue")
apa_sumtable <- bg(apa_sumtable, part = "body", i = c(25), 
                   bg = "turquoise")

# Set table properties
apa_sumtable <- set_table_properties(apa_sumtable, width = 1, layout = "autofit", align = "center")

# Save flextable to word
format_table <- prop_section(
  page_size = page_size(orient = "landscape"))

flextable::save_as_docx(apa_sumtable, path = "Z:/PsyThera/Projekte_Meinke/Systematic_review/4_PROBAST_assessment/PROBAST.docx", pr_section = format_table)
```
